name: ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            go-build-cache-dir
            go-mod-cache-dir
          key: go-build-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: go-build-${{ runner.os }}

      # - name: check dir 2
      #   run: |
      #     ls go-build-cache-dir
      #     ls go-mod-cache-dir
          
      - name: inject cache
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "go-build-cache-dir": "/root/.cache/go-build",
              "go-mod-cache-dir": "/go/pkg/mod/"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
      
      - name: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: check dir 3
      #   run: |
      #     ls go-build-cache-dir
      #     ls go-mod-cache-dir
